apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unprivileged-psp
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - restricted
  verbs:
  - use
