apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unprivileged-rbac
rules:
- apiGroups: [""]
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "create", "update", "list"]
