apiVersion: v1
kind: Pod
metadata:
  name: root-container
spec:
  hostPID: true
  containers:
  - name: alpine
    image: alpine
    command: ["tail"]
    args: ["-f", "/dev/null"]
    securityContext:
      privileged: true
